---
title: "Editor Reviews"
execute:
  echo: false
format: 
  html:
    fig-width: 8
    fig-height: 4
    code-fold: false
---

```{r load-pkg-ed-rev, echo = FALSE, message = FALSE}
library (dashboard)
library (gt)
library (ggplot2)
library (tidyr)
library (dplyr)
library (viridis)
```

```{r get-ed-dat, echo = FALSE, message = FALSE}
#| cache: true
ed_dat <- editor_status (quiet = TRUE)
```
```{r prepro-ed-dat}
#| cache: false
ed_reviews <- ed_dat$reviews
ojs_define (ed_reviews_in = ed_reviews)
```

This panel provides data on reviews handled by each editor. Data are shown for
current editors only, with reviews listed from most to least recent.

```{ojs}
edReviews = transpose (ed_reviews_in)
// And get array of unique eds for input selector:
editorsAll = edReviews.map(function(item) {
    return item.editor;
});
editors = Array.from(new Set(editorsAll));
```

```{ojs}
viewof editor = Inputs.select(editors, {multiple: false, label: "Editor:"})
```

```{ojs}
filtered = edReviews.filter(function(ed) {
  return editor.includes(ed.editor)
})
n_filtered = filtered.length;
```

```{ojs}
numberColumn = "number"
Inputs.table(filtered, {
    showIndex: true,
    format: {
      [numberColumn]: d => htl.html`<a href="https://github.com/ropensci/software-review/issues/${d}">${d}</a>`,
    },
    columns: ["number", "title", "state", "opened_at", "closed_at"],
    sortBy: [numberColumn],
    reverse: true,
})
```



## Editor Reviews

This panel provides data on reviews handled by each editor. Data are shown for
current editors only, with reviews listed from most to least recent.

## Editor Reviews (Old)

```{r prepro-ed-dat-old, echo = FALSE}
ed_reviews <- ed_dat$reviews
ed_reviews <- split (ed_reviews, f = as.factor (ed_reviews$editor))
ed_reviews <- lapply (ed_reviews, function (i) {
    i$editor <- NULL
    return (i)
})
```

```{r ed-rev, echo = FALSE, message = FALSE, results = 'asis'}
u <- "https://github.com/ropensci/software-review/issues/"
for (i in seq_along (ed_reviews)) {
    this_ed <- names (ed_reviews) [i]
    this_tab <- ed_reviews [[i]]
    this_tab <- this_tab [order (this_tab$number, decreasing = TRUE), ]
    num_rev <- nrow (this_tab)
    rev_noun <- ifelse (num_rev == 1, "Review", "Reviews")
    cat (paste0 (
        "## [",
        this_ed,
        "](https://github.com/",
        this_ed,
        ")\n\n"
    ))
    this_tab$number <- paste0 (
        "<a href=",
        u,
        this_tab$number,
        ">",
        this_tab$number,
        "</a>"
    )
    this_tab$number <- lapply (this_tab$number, gt::html)
    tab <- gt::gt (this_tab) |>
        gt::tab_header (paste0 (
            num_rev,
            " ",
            rev_noun,
            " for [@",
            this_ed,
            "](https://github.com/",
            this_ed,
            ")"
        )) |>
        dashboard:::add_bg_colours ()

    print (tab)
}
```
