on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:

  quarto-build-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install sysdeps
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          folder: quarto
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}
